# Generated by Django 2.2.3 on 2019-07-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190731_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Showed', 'Showed')], default='Pending', max_length=10),
        ),
    ]
