# Generated by Django 2.2.3 on 2019-07-31 00:51

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=leads.models.upload_file_name),
        ),
    ]
